spring.data.redis.host=you_redis_host

spring.data.redis.port=6379

spring.data.redis.password=you_redis_password

spring.data.redis.database=0

spring.data.redis.timeout=1800000

spring.data.redis.lettuce.pool.max-active=20

spring.data.redis.lettuce.pool.max-wait=-1

spring.data.redis.lettuce.pool.max-idle=5

spring.data.redis.lettuce.pool.min-idle=0