server:
  port: 9093
spring:
  application:
    name: xiangwei-system
  datasource:
    username: root
    password: 123456
    # 连接到新创建的系统逻辑库
    url: jdbc:mysql://localhost:3306/xiangwei_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #配置主键自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启数据库下划线字段到 Java 驼峰属性的自动映射
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: '*'