spring:
  application:
    name: xiangwei-commodity
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiangwei_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  enabled: true
  tx-service-group: order_tx_group
  service:
    vgroup-mapping:
      order_tx_group: default  # 这里的 default 是 Seata 服务端默认的集群名称
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #配置主键自增
  configuration:
    #这里我们配置输出底层的sql,方便我们观察sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名自动映射 (如 merchantId -> merchant_id)
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*'